[project]
name = "sigtemplate"
version = "0.0.2"
authors = [
  { name="Ankhbold Batbaatar", email="ankhasgreens@gmail.com" },
  { name="Bhushith Gujjala Hari", email="haribhushith9999@gmail.com" },
]
description = "Special Interest Group on Templates"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/Sigbovik-Tokyo/sigtemplate"
Issues = "https://github.com/Sigbovik-Tokyo/sigtemplate/issues"

[build-system]
requires = ["uv_build >= 0.12.1, <0.13.0"]
build-backend = "uv_build"
